### ISSUE TITLE
Credits page

### ISSUE THREAD

**Issue by ICEREG1992** [ICEREG1992/fungwafrenzy#2]
## Describe the addition

Create the page for when you click the credits button.

## Context

Here we can credit all the people who worked on the project, with special thanks to Jamie Niemasik, Thomas Bender, Jacob Bakkila, and the rest of the Synydyne team. Also special thanks to 400TACOS, HUNDOBILLION, and LASERHAVER3.

## Proposed Solution

Fill out the `Credits()` function in `App.tsx` to create the page content. Doesn't need anything fancy other than text. Use the NET css classes for styling.

**Comment by Geeknerd1337** [comment]
Basic version added
